# Generated by Django 5.0.6 on 2024-06-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='cover_image',
            new_name='image',
        ),
    ]
