# Generated by Django 5.0.6 on 2024-06-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitles',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Субтитры'),
        ),
        migrations.AlterField(
            model_name='timing',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Тайминг'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Голос'),
        ),
    ]
